motor_topic: cmd_vel
encoder_topic: encoder
velocity_topic: velocity
gain:
  p: 15.0
  i: 50.0
  d: -0.5
output_min: -30.0
output_max: 30.0
velocity_timeout: 2.0
reverse_direction: false
wheel_encoder_tics_per_rev: 897.96
